# See https://github.com/marketplace/actions/helm-chart-testing
name: Helm Lint and Test Charts
on:
  push:
jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Helm setup
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Set up helm chart testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Lint the helm charts
        run: ct lint --chart-dirs . --charts . --target-branch ${{ github.event.repository.default_branch }}

