name: Lint using helm's builtin
on:
  push:
jobs:
  lint-helm-ceres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint ceres chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./ceres/
  lint-helm-tycho:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint tycho chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./tycho/
  package-helm-tycho:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Package the tycho chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package ./tycho/
  package-helm-ceres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Package the ceres chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package ./ceres/
  release-helm-ceres:
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ceres-0.1.0.tar.gz"
  release-helm-tycho:
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "tycho-0.1.0.tar.gz"

